### ISSUE TITLE
Settings tooltips won't go away

### ISSUE THREAD

**Issue by BobbyBobster** [DaniGuardiola/TimeDoser#10]
On my Toshiba Chromebook 2, the tooltip information appears when my cursor moves over the different items but won't disappear.

I've added a screenshot of the problem:
![timedosertooltipproblem](https://cloud.githubusercontent.com/assets/23128298/24325802/4bddf7a2-11a1-11e7-935b-1b0478359993.png)

**Comment by ghost** [comment]
I had uninstalled Time Doser because it stops working too often. I came back to it this week because there really isn't a better timer out there (although it still hangs). The new version is doing exactly what BobbyBobster described. When I mouse over each option, the tooltip appears but won't go away, even when I exit settings and go back into them. (Windows 10 Creators Update, Samsung Notebook 9)

**Comment by DaniGuardiola** [comment]
@BobbyBobster @rhanajoy stay tuned ;)

**Comment by ghost** [comment]
Can't wait! :)

**Comment by DaniGuardiola** [comment]
@BobbyBobster @rhanajoy TimeDoser v2 is being retired, so I'm closing all issues. v3 is in the works, and it should replace v2 once I'm done. Thanks for your interest!
